language: node_js
node_js:
  - 4.2.4
  - 5.4.0
# Add build chain config for Node GYP in Node 4.x
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
install:
  - npm install npm -g
  - npm install phantomjs -g
  - npm install
script:
  - npm test
